export type Env = {
  ACP_RELAY_ACCOUNT_SESSION_KEY_ID?: string;
  ACP_RELAY_ACCOUNT_SESSION_PRIVATE_KEY?: string;
  ACP_RELAY_ACCOUNT_SESSION_PUBLIC_KEYS?: string;
  ACP_RELAY_CONTROL_PLANE_SECRET?: string;
  ACP_RELAY_CLIENT_RECONNECT_GRACE_MS?: string;
  ACP_RELAY_HOST_RECONNECT_GRACE_MS?: string;
  ACP_RELAY_DB?: D1Database;
  ACP_RELAY_GITHUB_CLIENT_ID?: string;
  ACP_RELAY_GITHUB_CLIENT_SECRET?: string;
  ACP_RELAY_HEARTBEAT_INTERVAL_MS?: string;
  ACP_RELAY_HEARTBEAT_TIMEOUT_MS?: string;
  ACP_RELAY_MAX_BUFFERED_FRAMES_PER_CONNECTION?: string;
  ACP_RELAY_MAX_QUEUED_FRAMES_PER_CONNECTION?: string;
  ACP_RELAY_MAX_CONNECTIONS_PER_ACCOUNT?: string;
  ACP_RELAY_PENDING_HOST_REQUEST_TIMEOUT_MS?: string;
  ACP_RELAY_SHARDS: DurableObjectNamespace;
  ACP_RELAY_WORKBENCH_ORIGIN?: string;
  FREE_OTLP_ENDPOINT?: string;
  FREE_OTLP_HEADER?: string;
  FREE_OTLP_TOKEN?: string;
};

export const UPGRADE_REQUIRED = "Expected WebSocket upgrade.";
